version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule: 
      interval: monthly
      
  - package-ecosystem: docker
    directories:
      - /build/migrator/
      - /build/service/
    schedule: 
      interval: monthly
      
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
