all: true
disable-version-string: true
with-expecter: true
mockname: "Mock{{.InterfaceName | camelcase}}"
filename: "{{.InterfaceName | camelcase | firstLower}}.go"
outpkg: "{{.PackageName}}_test"
issue-845-fix: true
dir: 'internal/generated/mocks/{{replaceAll .PackagePath "github.com/nijeti/cinema-keeper/internal" ""}}'
packages:
  github.com/nijeti/cinema-keeper/internal:
    config:
      recursive: true
