services:   
  db:
    image: postgres:17-alpine3.21
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      start_period: 10s
      start_interval: 1s
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - network
    volumes:
      - db:/var/lib/postgresql/data
  
  migrator:
    image: ghcr.io/nijeti/cinema-keeper-migrator:${VERSION-latest}
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB__CONNECTION_STRING: ${DB_CONNECTION_STRING}
    networks:
      - network

  service:
    image: ghcr.io/nijeti/cinema-keeper-service:${VERSION-latest}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      start_period: 10s
      start_interval: 1s
      interval: 1m
      timeout: 20s
      retries: 3
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_completed_successfully
    environment:
      DISCORD__TOKEN: ${SERVICE_DISCORD_TOKEN}
      DB__CONNECTION_STRING: ${DB_CONNECTION_STRING}
    networks:
      - network

networks:
  network:

volumes:
  db:
